### ISSUE TITLE
Issue with way/generators

### ISSUE THREAD

**Issue by phirschybar** [morrislaptop/LaravelFivePackageBridges#5]
Thanks for building this bridge package! On a fresh L5 install I am getting:

```
$ php artisan generate:migration create_foo_table
exception 'Way\Generators\Filesystem\FileNotFound' in /var/www/laravel-5-sandbox/www/vendor/way/generators/src/Way/Generators/Filesystem/Filesystem.php:45
Stack trace:
#0 /var/www/laravel-5-sandbox/www/vendor/way/generators/src/Way/Generators/Generator.php(51): Way\Generators\Filesystem\Filesystem->get(NULL)
#1 /var/www/laravel-5-sandbox/www/vendor/way/generators/src/Way/Generators/Generator.php(33): Way\Generators\Generator->compile(NULL, Array, Object(Way\Generators\Compilers\TemplateCompiler))
#2 /var/www/laravel-5-sandbox/www/vendor/way/generators/src/Way/Generators/Commands/GeneratorCommand.php(65): Way\Generators\Generator->make(NULL, Array, '/2015_02_08_143...')
#3 /var/www/laravel-5-sandbox/www/vendor/way/generators/src/Way/Generators/Commands/MigrationGeneratorCommand.php(29): Way\Generators\Commands\GeneratorCommand->fire()
#4 [internal function]: Way\Generators\Commands\MigrationGeneratorCommand->fire()
#5 /var/www/laravel-5-sandbox/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#6 /var/www/laravel-5-sandbox/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /var/www/laravel-5-sandbox/www/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/laravel-5-sandbox/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/laravel-5-sandbox/www/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/laravel-5-sandbox/www/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Way\Generators\Commands\MigrationGeneratorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/laravel-5-sandbox/www/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/laravel-5-sandbox/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/laravel-5-sandbox/www/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
```

**Comment by morrislaptop** [comment]
Let me check

**Comment by morrislaptop** [comment]
It's just worked for me... Here are the steps I took
- `laravel new bridges-issue-5`
- `cd bridges-issue-5`
- `composer require morrislaptop/laravel-five-package-bridges`
- `composer require way/generators`
- Added the 'Morrislaptop\LaravelFivePackageBridges\ConfigServiceProvider' and 'Morrislaptop\LaravelFivePackageBridges\Bridges\GeneratorsServiceProvider' to config/app.php
- `php artisan generate:migration create_foo_table`

You will get an exception regarding dump autoload however the migration file is created correctly.
